// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutritionApi.Infrastructure.Persistence;

#nullable disable

namespace NutritionApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutritionApi.Domain.Entity.Diet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CalorieTarget")
                        .HasColumnType("integer")
                        .HasColumnName("calorie_target");

                    b.Property<string>("DietType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("diet_type");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("StatusDiet")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("diet_status");

                    b.Property<float>("TargetWeight")
                        .HasColumnType("real")
                        .HasColumnName("target_weight");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_diets");

                    b.HasIndex("StatusDiet")
                        .HasDatabaseName("ix_diets_diet_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_diets_user_id");

                    b.ToTable("diets", (string)null);
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.DietPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DietType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("diet_type");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("goal");

                    b.Property<bool>("IsTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<float>("TargetWeight")
                        .HasColumnType("real")
                        .HasColumnName("target_weight");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_diet_plans");

                    b.HasIndex("IsTemplate")
                        .HasDatabaseName("ix_diet_plans_is_template");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_diet_plans_user_id");

                    b.ToTable("diet_plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            DietType = "Balanced",
                            Goal = "WeightLoss",
                            IsTemplate = true,
                            Name = "Perte de poids",
                            TargetWeight = 0f
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            DietType = "Balanced",
                            Goal = "Maintenance",
                            IsTemplate = true,
                            Name = "Maintien",
                            TargetWeight = 0f
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            DietType = "HighProtein",
                            Goal = "WeightGain",
                            IsTemplate = true,
                            Name = "Prise de masse",
                            TargetWeight = 0f
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            DietType = "Mediterranean",
                            Goal = "Maintenance",
                            IsTemplate = true,
                            Name = "Équilibre méditerranéen",
                            TargetWeight = 0f
                        });
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string[]>("AllergensTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("allergens_tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<float>("CaloriesPer100g")
                        .HasColumnType("real")
                        .HasColumnName("calories_per_100g");

                    b.Property<int>("CarbsPer100g")
                        .HasColumnType("integer")
                        .HasColumnName("carbs_per_100g");

                    b.Property<int>("FatsPer100g")
                        .HasColumnType("integer")
                        .HasColumnName("fats_per_100g");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("OffId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("off_id");

                    b.Property<int>("ProteinsPer100g")
                        .HasColumnType("integer")
                        .HasColumnName("proteins_per_100g");

                    b.HasKey("Id")
                        .HasName("pk_food_items");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_food_items_name");

                    b.HasIndex("OffId")
                        .IsUnique()
                        .HasDatabaseName("ix_food_items_off_id");

                    b.ToTable("food_items", (string)null);
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_saved");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meal_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_meals");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_meals_user_id");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_item_id");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_id");

                    b.Property<float>("Quantity")
                        .HasColumnType("real")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_meal_items");

                    b.HasIndex("FoodItemId")
                        .HasDatabaseName("ix_meal_items_food_item_id");

                    b.HasIndex("MealId")
                        .HasDatabaseName("ix_meal_items_meal_id");

                    b.ToTable("meal_items", (string)null);
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.SavedFoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_item_id");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_food_items");

                    b.HasIndex("FoodItemId")
                        .HasDatabaseName("ix_saved_food_items_food_item_id");

                    b.HasIndex("UserId", "FoodItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_food_items_user_id_food_item_id");

                    b.ToTable("saved_food_items", (string)null);
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("activity_level");

                    b.Property<string[]>("Allergies")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("allergies")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string[]>("DietaryPreferences")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("dietary_preferences")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<float>("Height")
                        .HasColumnType("real")
                        .HasColumnName("height");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keycloak_id");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Free")
                        .HasColumnName("subscription_tier");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_keycloak_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.WeightEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("MeasuredAt")
                        .HasColumnType("date")
                        .HasColumnName("measured_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_weight_entries");

                    b.HasIndex("MeasuredAt")
                        .HasDatabaseName("ix_weight_entries_measured_at");

                    b.HasIndex("UserId", "MeasuredAt")
                        .IsUnique()
                        .HasDatabaseName("ix_weight_entries_user_id_measured_at");

                    b.ToTable("weight_entries", (string)null);
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.Diet", b =>
                {
                    b.HasOne("NutritionApi.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diets_users_user_id");

                    b.OwnsOne("NutritionApi.Domain.ValueObjects.MacroDistribution", "MacroDistribution", b1 =>
                        {
                            b1.Property<Guid>("DietId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("CarbPercentage")
                                .HasColumnType("integer")
                                .HasColumnName("macro_carb_pct");

                            b1.Property<int>("FatPercentage")
                                .HasColumnType("integer")
                                .HasColumnName("macro_fat_pct");

                            b1.Property<int>("ProteinPercentage")
                                .HasColumnType("integer")
                                .HasColumnName("macro_protein_pct");

                            b1.HasKey("DietId");

                            b1.ToTable("diets");

                            b1.WithOwner()
                                .HasForeignKey("DietId")
                                .HasConstraintName("fk_diets_diets_id");
                        });

                    b.Navigation("MacroDistribution")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.DietPlan", b =>
                {
                    b.HasOne("NutritionApi.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_diet_plans_users_user_id");

                    b.OwnsOne("NutritionApi.Domain.ValueObjects.MacroDistribution", "MacroDistribution", b1 =>
                        {
                            b1.Property<Guid>("DietPlanId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("CarbPercentage")
                                .HasColumnType("integer")
                                .HasColumnName("macro_carb_pct");

                            b1.Property<int>("FatPercentage")
                                .HasColumnType("integer")
                                .HasColumnName("macro_fat_pct");

                            b1.Property<int>("ProteinPercentage")
                                .HasColumnType("integer")
                                .HasColumnName("macro_protein_pct");

                            b1.HasKey("DietPlanId");

                            b1.ToTable("diet_plans");

                            b1.WithOwner()
                                .HasForeignKey("DietPlanId")
                                .HasConstraintName("fk_diet_plans_diet_plans_id");

                            b1.HasData(
                                new
                                {
                                    DietPlanId = new Guid("11111111-1111-1111-1111-111111111101"),
                                    CarbPercentage = 35,
                                    FatPercentage = 30,
                                    ProteinPercentage = 35
                                },
                                new
                                {
                                    DietPlanId = new Guid("11111111-1111-1111-1111-111111111102"),
                                    CarbPercentage = 45,
                                    FatPercentage = 30,
                                    ProteinPercentage = 25
                                },
                                new
                                {
                                    DietPlanId = new Guid("11111111-1111-1111-1111-111111111103"),
                                    CarbPercentage = 50,
                                    FatPercentage = 20,
                                    ProteinPercentage = 30
                                },
                                new
                                {
                                    DietPlanId = new Guid("11111111-1111-1111-1111-111111111104"),
                                    CarbPercentage = 50,
                                    FatPercentage = 30,
                                    ProteinPercentage = 20
                                });
                        });

                    b.Navigation("MacroDistribution")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.Meal", b =>
                {
                    b.HasOne("NutritionApi.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meals_users_user_id");
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.MealItem", b =>
                {
                    b.HasOne("NutritionApi.Domain.Entity.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meal_items_food_items_food_item_id");

                    b.HasOne("NutritionApi.Domain.Entity.Meal", null)
                        .WithMany("MealItems")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meal_items_meals_meal_id");

                    b.OwnsOne("NutritionApi.Domain.ValueObjects.NutritionInfo", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("MealItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<float>("Calories")
                                .HasColumnType("real")
                                .HasColumnName("nutrition_calories");

                            b1.Property<int>("Carbs")
                                .HasColumnType("integer")
                                .HasColumnName("nutrition_carbs");

                            b1.Property<int>("Fats")
                                .HasColumnType("integer")
                                .HasColumnName("nutrition_fats");

                            b1.Property<int>("Proteins")
                                .HasColumnType("integer")
                                .HasColumnName("nutrition_proteins");

                            b1.HasKey("MealItemId");

                            b1.ToTable("meal_items");

                            b1.WithOwner()
                                .HasForeignKey("MealItemId")
                                .HasConstraintName("fk_meal_items_meal_items_id");
                        });

                    b.Navigation("FoodItem");

                    b.Navigation("Nutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.SavedFoodItem", b =>
                {
                    b.HasOne("NutritionApi.Domain.Entity.FoodItem", null)
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_food_items_food_items_food_item_id");

                    b.HasOne("NutritionApi.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_food_items_users_user_id");
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.WeightEntry", b =>
                {
                    b.HasOne("NutritionApi.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weight_entries_users_user_id");
                });

            modelBuilder.Entity("NutritionApi.Domain.Entity.Meal", b =>
                {
                    b.Navigation("MealItems");
                });
#pragma warning restore 612, 618
        }
    }
}
